### ISSUE TITLE
Namespace error in Model/SecondChanceRepository.php

### ISSUE THREAD

**Issue by MatthijsBreed** [buckaroo-it/Magento2_SecondChance#19]
Row 590 of Model/SecondChanceRepository.php uses `Type::TYPE_SIMPLE`
which results in `PHP Fatal error:  Uncaught Error: Class 'Buckaroo\Magento2SecondChance\Model\Type' not found`

Presumably, this refers to `Magento\Catalog\Model\Product\Type::TYPE_SIMPLE` which is 'simple'

Fix, add `use Magento\Catalog\Model\Product\Type;` to the use-block

**Comment by Buckaroo-Rene** [comment]
Thanks again for informing us about this issue.
I will close this issue since it was open for a long time and already resolved.
